### ISSUE TITLE
Training Checklist

### ISSUE THREAD

**Issue by pagnmickie** [pagnmickie/training#1]
## Spring-related and Java debugging with IntelliJ
- [ ] https://app.pluralsight.com/library/courses/spring-fundamentals - 3 hours
- [ ] https://app.pluralsight.com/library/courses/spring-boot-first-application - 2+ hours
- [ ] https://app.pluralsight.com/library/courses/architecting-web-applications-spring - 2 hours
- [ ] https://app.pluralsight.com/library/courses/spring-data-jpa-getting-started - 3+ hours
- [ ] Building Microservices with Spring Boot LiveLessons (Video Training) by Josh Long / Phillip Webb – 6+ hours https://www.jetbrains.com/help/idea/2016.3/debugging.html

## JavaScript-related and debugging with Chrome
- [ ] https://app.pluralsight.com/library/courses/javascript-programming-basics - 2+ hours 
- [ ] https://app.pluralsight.com/library/courses/play-by-play-learning-angularjs-ken-cenerelli-john-papa - 1.5 hours
- [ ] https://app.pluralsight.com/library/courses/angularjs-fundamentals - 7 hours
- [ ] https://app.pluralsight.com/library/courses/angularjs-ngmock-unit-testing - 2+ hours
- [ ] https://app.pluralsight.com/library/courses/building-components-angular-1-5 - 2 hours
- [ ] https://www.youtube.com/watch?v=FGK3VYUSBog - only 20 minutes
- [ ] https://skillsmatter.com/skillscasts/7924-effective-javascript-debugging-with-chrome-devtools - maybe?
